---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nine-nineinfra-tech-v1alpha1-ninecluster
  failurePolicy: Fail
  name: mninecluster.kb.io
  rules:
  - apiGroups:
    - nine.nineinfra.tech
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nineclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nine-nineinfra-tech-v1alpha1-ninecluster
  failurePolicy: Fail
  name: vninecluster.kb.io
  rules:
  - apiGroups:
    - nine.nineinfra.tech
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nineclusters
  sideEffects: None
